name: GitHub Actions Demo
on:
  pull_request:
    paths-ignore:
      - '.github/**'
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event: ${{ github.event_name }}"
          echo "branch: ${{ github.ref }}."

      - uses: actions/checkout@v4

      - name: List files in the repository
        run: tree


