name: GitHub Actions Demo
on:
  pull_request:
    paths-ignore:
      - '.github/**'
    branches:
      - main
  push:
    branches:
      -main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    

