name: Test Docker action
on:
  push:
    branches: 
      - main
    paths:
      - 'hello-world-docker-ation/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run docker
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@JRuiCosta'

      - name: Write Summary Output
        run: | 
          echo "Demo Summary Output :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "The `time` from out custom action is ${{ steps.hello-action.outputs.time }}" >> $GITHUB_STEP_SUMMARY
